# Site settings
title: Language Of Shakespeare Plays
baseurl: ""
url: ""
exclude: ["vendor"]
permalink: "pretty"

collections:
    analyses:
        permalink: "/:collection/:path/"
        output: true

defaults:
    -
        scope:
            path: ""
            type: "analyses"
        values:
            layout: "page"

markdown: "kramdown"
