# Site settings
title: Language Of Shakespeare Plays
baseurl: ""
url: ""
exclude: ["vendor"]

collections:
    analyses:
        output: true

# Build settings
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
