# Site settings
title: Language Of Shakespeare Plays
baseurl: ""
url: ""
exclude: ["vendor"]
permalink: "pretty"

collections:
    analyses:
        output: true

defaults:
    -
        values:
            layout: "page"
    -
        scope:
            type: "analyses"
        values:
            layout: "analysis"

markdown: "kramdown"
